dist: xenial
language: python

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8

script: 
  - black --check .
  - pytest --flake8 

after_success:
  - coveralls