dist: xenial
language: python

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coverage
  - pip install coveralls

script: 
  - black .
  - flake8 .

after_success:
  - coveralls